
---
- name: Extend LVM partition...
  vars_files:
    - ex.yml  
  hosts: lvm
  gather_facts: no
  become: true


  tasks:

    - name: Read device information (always use unit when probing)
      community.general.parted: device=/dev/sda2 unit=GiB
      register: sda_info


    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: sda_info    
        

    - name: Extend an existing partition to fill all available space
      community.general.parted:
        device: /dev/sda
        number: 2
        part_end: "100%"
        resize: true
        state: present